services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    environment:
      - PORT=:3000
      - AUTH_SVC_URL=ath-svc:50051
      # - PRODUCT_SVC_URL=product-svc:50052
      # - ORDER_SVC_URL=order-svc:50053
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app
    depends_on:
      - auth-svc
    restart: always

  auth-svc:
    build:
      context: ./auth-svc
      dockerfile: Dockerfile.dev
    container_name: auth-svc
    volumes:
      - ./auth-svc:/app
    ports:
      - "50051:50051"
    # environment:
    #   - PORT=:50051
    #   - DB_URL=postgres://postgres:postgres@auth-db:5432/auth_svc
    #   - JWT_SECRET_KEY=h28dh582fcu390
    # depends_on:
    #   - auth-db
    restart: always


