FROM golang:1.24.3 

WORKDIR /app 

COPY . .

RUN go install github.com/githubnemo/CompileDaemon@latest
ENV PATH="/go/bin:${PATH}"

# remove package not used in go.mod with update go.sum
RUN go mod tidy
RUN go mod download 

EXPOSE 50051

CMD ["CompileDaemon", "--build=go build -o main ./cmd/main.go", "--command=./main"]